### ISSUE TITLE
Some Comment Tags Break on Format

### ISSUE THREAD

**Issue by erier** [mutian/Sublime-CSS-Format#24]
First, excellent plugin! I use it all the time.

I came across a bit of an issue today, however.

Whenever there are comments like this:
```
/********************/
/* HERE's A SAMPLE */
/********************/
```

and CSS Format is run, it comes out like this:
```
/******************** /
/* HERE's A SAMPLE */
/******************** /
```

As you can see by the end of this output `/******************** /`, this is not good for the CSS that follows the comment as the comment hasn't been closed.

I've gone ahead and taken out all instances of `/********************/` in my work to avoid the issue, but others may miss this and not be so lucky.

_Before Formatting_
![screen shot 2014-11-20 at 5 21 36 pm](https://cloud.githubusercontent.com/assets/844438/5134299/bdec3b34-70da-11e4-97f5-6bcf4eb77363.png)
_After Formatting_
![screen shot 2014-11-20 at 5 22 08 pm](https://cloud.githubusercontent.com/assets/844438/5134300/bdf2802a-70da-11e4-9ab2-eef111727126.png)

Cheers -

**Comment by thecotne** [comment]
problem with comments still exists

before
![before](https://cloud.githubusercontent.com/assets/1606993/5625703/5db42bb2-9599-11e4-8bad-2a2b33a6bace.PNG)

after
![after](https://cloud.githubusercontent.com/assets/1606993/5625702/5db3116e-9599-11e4-8342-7348f8597f3e.PNG)


before
![before](https://cloud.githubusercontent.com/assets/1606993/5625713/ab4c282a-9599-11e4-93c9-91b0ece035f1.PNG)

after
![after](https://cloud.githubusercontent.com/assets/1606993/5625712/ab4a18be-9599-11e4-8838-dd1c34d5660b.PNG)

**Comment by mutian** [comment]
Hi, I've optimized this formater, it will keep the content format in comments, so the code like this
![comment1](https://cloud.githubusercontent.com/assets/1606993/5625703/5db42bb2-9599-11e4-8bad-2a2b33a6bace.PNG)
and this
![comment2](https://cloud.githubusercontent.com/assets/1606993/5625713/ab4c282a-9599-11e4-93c9-91b0ece035f1.PNG)
are both ok.


In order to adapt to more usage scenarios, it will add new line break between comment blocks, so the code like this
```
/*** Components ***/
/** Content Objects **/
/* form */
```
will format to:
```
/*** Components ***/

/** Content Objects **/

/* form */
```

But the code like this
```
/********************/
/* HERE's A SAMPLE */
/********************/
```
will be also formatting to:
```
/********************/

/* HERE's A SAMPLE */

/********************/
```

Hope I can meet your needs.
